### ISSUE TITLE
Hydra is broken in the latest nightly

### ISSUE THREAD

**Issue by miversen33** [nvim-island/hydra.nvim#3]
This issue is what prompted this fork.

I am not entirely sure what is going on, but as of v0.10.0-dev-4880385 hydra just kind of falls apart.

Commands no longer function properly, pink hydras are formatted weird in their floating windows, opening neo-tree seems to sort of fail now, etc.

I do not have a minimum reproducible configuration for this yet (nor do I have all the things that broke here) but since this is my issue, this can be a "just trust me bro" moment.

I will update this description with the various issues as I find them and this may get broken into tasks or smaller piecemeal issues.

**Comment by miversen33** [comment]
Reference [#102](https://github.com/anuvyklack/hydra.nvim/issues/102)

**Comment by miversen33** [comment]
I have found that hydra still functions "properly" as of neovim-0.10.0-dev-ebe nightly, but I am unsure how to get that nightly back without having to go recompile at that point. In any case, I am able to have hydra "functioning" on this older version and thus I can compare between that older nightly and current to try and figure out differences

**Comment by miversen33** [comment]
Here is a minimum reproducible configuration that can be used to recreate this issue.

This configuration "works as expected" on the above listed neovim version (0.10.0-dev-ebe) and falls apart on current nightly (0.10.0-dev-488).

Falls apart so far being the following things

- Hydras do not close out when they reach their head
- Hint printing is broken as hell, but only sometimes (see screenshot)
![image](https://github.com/nvim-island/hydra.nvim/assets/2640668/d33bea3d-8625-4c2d-b542-ed3e6e51ef0f)

```lua
-- Minimal configuration
-- mini.lua
-- Use with the --clean -u flags. EG nvim --clean -u mini.lua
-- This config will create a temp directory and will blow away that temp directory
-- everytime this configuration is loaded. Great for simulating a new installation
-- of a plugin

-- Setting some basic vim options
-- Some junk because I am sick of formatting tables in print
local _print = _G.print
local clean_string = function(...)
    local args = { n = select("#", ...), ... }
    local formatted_args = {}
    for i = 1, args.n do
        local item = select(i, ...)
        if not item then item = 'nil' end
        local t_type = type(item)
        if t_type == 'table' or t_type == 'function' or t_type == 'userdata' then
            item = vim.inspect(item)
        end
        table.insert(formatted_args, item)
    end
    return table.concat(formatted_args, ' ')
end
_G.print = function(...)
    _print(clean_string(...))
end

vim.opt.mouse = 'a'
vim.opt.termguicolors = true
-- If you want to play around with this, you can set the do_clean
-- variable to false. This will allow changes made to
-- underlying plugins to persist between sessions, while
-- still keeping everything in its own directory so
-- as to not affect your existing neovim installation.
--
-- Setting this to true will result in a fresh clone of
-- all modules
local do_clean = true
local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or
'/'                                                                              -- \ for windows, mac and linux both use \
local root = vim.fn.fnamemodify("./.repro", ":p")
if vim.loop.fs_stat(root) and do_clean then
    print("Found previous clean test setup. Cleaning it out")
    -- Clearing out the mods directory and recreating it so
    -- you have a fresh run everytime
    vim.fn.delete(root, 'rf')
end

-- DO NOT change the paths and don't remove the colorscheme

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "nvim-island/hydra.nvim",
        config = function()
            local cmd = require("hydra.keymap-util").cmd
            local hydra = require("hydra")
            hydra({
                name = "Test Commands",
                mode = { "n" },
                hint = [[
                Test Commands
                ^
                _a_: Print Message
                ^
                ^ ^                              _q_/_<Esc>_: Exit Hydra
                ]],
                config = {
                    color = 'teal',
                    invoke_on_body = true,
                    hint = {
                        type = 'window',
                        position = 'bottom',
                        border = 'rounded',
                        show_name = true
                    }
                },
                body = 'f',
                heads = {
                    { "a", cmd 'lua print("Hello From Hydra Test Command")<CR>', { desc = "Test Command" } },
                    { "q", nil, {
                        desc = "quit",
                        exit = true,
                        nowait = true
                    } },
                    { "<Esc>", nil, {
                        desc = "quit",
                        exit = true,
                        nowait = true
                    } }
                }
            })
        end
    },
    -- add any other plugins here
}

require("lazy").setup(plugins, {
    root = root .. "/plugins"
})

vim.opt.splitright = true
vim.opt.splitbelow = true

vim.cmd.colorscheme("tokyonight")
-- add anything else here

```

**Comment by vsedov** [comment]
Yeah it gets worse from what i can tell too as the hydra hint remains constant; such that you get stuff like this : 

![image](https://github.com/nvim-island/hydra.nvim/assets/28804392/67f58af8-d057-418e-ae49-6578de5fac05)
Harpoon issue linked with the hydra pretty much. 

Il spend some time today seeing if i can fix it, let you know if i come up with anything mate.

**Comment by miversen33** [comment]
@vsedov My current suspicion is that it is related to the commands being triggered while focus is on a floating window. Shit makes no sense to me, but I have boiled it down to a point where I can see the exact lua commands that hydra is firing and if I manually run the commands, they work just fine. 

Another theory I have is that it is something to do with the [hydra.wait](https://github.com/nvim-island/hydra.nvim/blob/master/lua/hydra/init.lua#L488-L490) function as that is tied to every command being ran. I can verify that removing the "exit" command does not fix the issue which indicates that the problem arises during the execution of the vim commands.

I tried swapping out `api.nvim_feedkeys` with `api.nvim_command` but that did not fix the issue either. I reached out to the [neo-tree team](https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/1243) hoping to maybe get some clarify from their side as to what could be causing this issue.

**Comment by miversen33** [comment]
Dropping my nvim log here. Something interesting, this error

> not found in runtime path: "ftplugin/hydra_hint[.]{vim,lua} ftplugin/hydra_hint_*.{vim,lua} ftplugin/hydra_hint/*.{vim,lua}"
not found in runtime path: "indent/hydra_hint[.]{vim,lua}"

[nvim.log](https://github.com/nvim-island/hydra.nvim/files/13443790/nvim.log)

**Comment by miversen33** [comment]
I am also seeing this "no filetype" issue when opening files with [telescope file explorerer](https://github.com/nvim-telescope/telescope-file-browser.nvim). This must be related to floating windows somehow

**Comment by vsedov** [comment]
Alright few updates, so i converted almost everything ot the new api, just to see if maybe i missed something; issue still remains, i also suspected it was something to do with hydra wait but no, was not that either.  At this point i might just start logging every possible event going on; as im not sure what else to do now.

**Comment by vsedov** [comment]
Well this is infuriating; there is a syntax error somewhere, for some reason with ftplugin which makes no sense ... and any time you open anything that has a floating application, tele, harpoon, or if you change a local setting like your vim options, poof it breaks. i heavily suspect it has to be something messed up in the lib folder, but honestly im not sure what. 

Ive resorted to logging every function, to figure out what set of functions could be causing it; will report back in a bit if i figure something out.

**Comment by vsedov** [comment]
Update 1: 

https://github.com/nvim-island/hydra.nvim/blob/48784785ff84d61374c38047d9bb13c1b18b11cd/lua/hydra/hint/window.lua#L349 

Removing this line, should fix the floating issue i think.  the floating window staying there, 

so i can finally close, harpoon or tele without this thing weirdly messing up the entire syntax and having the floating window just stay there

Can you double check this for me ?

**Comment by miversen33** [comment]
No dice on my side. Still seeing shit broken. I think you're onto something though, I think the issue is happening even before the command is being executed. I think the breaking is happening when the floating window is initially opened. I'm walking the stack right now to see if I can figure out where that might be happening

**Comment by vsedov** [comment]
Can i see a ss of what the min config shows ? 

![image](https://github.com/nvim-island/hydra.nvim/assets/28804392/c51a28bb-05e2-4831-9ab2-6c09aad4d8f6)
![image](https://github.com/nvim-island/hydra.nvim/assets/28804392/86715306-0a66-49ef-b49c-0dc0947f470a)

If you want i can make a pr on the changes i did, see if its viable for you perhaps ?

**Comment by miversen33** [comment]
What is an ss? I wouldn't do a PR though if you have a branch publicly available I can pull it down to get you what you are looking for.

Side note, I have narrowed the issue down to [HintAutoWindow:show](https://github.com/nvim-island/hydra.nvim/blob/master/lua/hydra/hint/window.lua#L105-L131). If you comment out the entire function contents, everything works (assuming you can operate without the floating window being visible). So it absolutely is something to do with the floating window creation.

**Comment by miversen33** [comment]
Fucking found it. Removing https://github.com/nvim-island/hydra.nvim/blob/master/lua/hydra/hint/window.lua#L111 fixes the syntax issues. I have no idea why that was enabled though so I am a bit hesitant to completely remove it.

It is enabled before the window creation and disabled again after window creation. My guess, this causing issues with syntax highlighting as the various `WinCreate`, `BufAdd`, etc events are not captured during the creation.

There has to be a good reason this was added but idk

**Comment by vsedov** [comment]
Oh well done mate, this was a complete rollercoaster, well so long as we get something working for now we can work on it later i guess. Might be wise to check the git history to see when it was added might be a nice commit somewhere. 

Alright, will hceck that branch now, 

Cheers.

**Comment by miversen33** [comment]
> Oh well done mate, this was a complete rollercoaster, well so long as we get something working for now we can work on it later i guess. Might be wise to check the git history to see when it was added might be a nice commit somewhere.
> 
> Alright, will hceck that branch now,
> 
> Cheers.

It was added as part of a bulk "refactor" [it looks like](https://github.com/miversen33/hydra.nvim/commit/c3060ff48549e91e75f4f130f2ad085de519ba29#diff-c4992764f49feea7e1aa3841a091e28dc2541812d0943750d6fc63810a5b3d37)

**Comment by vsedov** [comment]
Works like a charm mate. Good job, was a needed fix too; il ask around if anyone might know why this was there.

**Comment by miversen33** [comment]
Bet. Yoinking it and getting that merged into main

**Comment by vsedov** [comment]
Going to quickly revive for a bit: 


I spoke to @pysan3 

He stated the following 
"""
If u use neo-tree, it also disabled some autocmds in the preview window. [preview](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/common/preview.lua#L290)

This is to drastically improve the performance as we don’t need rich LSP or other fancy plugins that users installed to be there in the preview window, and what we need is only treesitter. 
I believe telescope is also doing something similar in the preview window on the right side (haven’t checked tho). 
I don’t use hydra so I’m not sure what that specific code was trying to do but I don’t think blindly deleting that line altogether is a good idea and will become a huge performance decrease. You should actually think and pick what autocmds to block. 

Deleting that kind of line without much testing and without careful consideration is VERY bad since it causes performance issues which is very difficult to diagnose
"""

**Comment by miversen33** [comment]
I had a feeling it had something to do with that. That said though, I would much prefer functional with poor performance over not functional at all and thus with that in mind, the fix will stay in place while we play around with getting the correct settings in place (even if the correct setting is using that exact line but moving it or something of that nature). I'll look into that later tomorrow probably

**Comment by miversen33** [comment]
Decided to poke this a bit more and I think I know what was actually going on.

It was not setting `vim.o.eventignore = 'all'` that was the issue, it was then setting it to `nil` that was the problem. So I am pushing up a [new branch (again)](https://github.com/miversen33/hydra.nvim/tree/fixed-eventignore). Behavior hasn't changed from the previous resolution (simply removing the line), however I put back the ignore all events logic.

https://github.com/miversen33/hydra.nvim/commit/0564eee84546811ef77d13e2c34241f0a6da2b25

@vsedov if you have a moment, could you test this to verify it is still "correct" for you as well? If so, I will merge this into main

**Comment by vsedov** [comment]
Yeah ofcourse 

Do give me moment

**Comment by miversen33** [comment]
Is really dead now
